export const APP_STRINGS: Record<string, string> = {
  tab_home: "Home",
  tab_loans: "Loans",
  tab_providers: "Providers",
  tab_advisor: "AI Advisor",
  tab_profile: "Profile",

  home_search_placeholder: "Search anything...",
  home_loan_overview: "Loan Overview",
  home_credit_score: "Credit Score",
  home_active_loan: "Active Loan",
  home_loan_activity: "Loan Activity",
  home_repayment_progress: "Repayment Progress",
  home_next_payment: "Next Payment",
  home_loans_completed: "Loans Completed",
  home_loans_completed_sub: "3 loans successfully paid",
  home_credit_health: "Credit Health",
  home_credit_health_sub: "Score trending upward",
  home_ai_loan_advisor: "AI Loan Advisor",
  home_suggestions_available: "5 Suggestions Available",
  home_get_personalized: "Get Personalized\nLoan Advice",
  home_ai_description: "AI-powered recommendations to improve your credit score and find the best loan rates.",
  home_start_conversation: "Start Conversation",
  home_loan_providers: "Loan Providers",
  home_see_all: "See All",
  home_repaid: "Repaid",
  home_no_active_loan: "No active loan",
  home_no_active_loan_sub: "Browse loan offers",
  home_repayment_none: "Nothing to repay yet",
  home_next_payment_none: "No payment due",
  home_days: "days",
  home_overdue: "Overdue",
  home_loans_paid_label: "loans successfully paid",
  home_credit_up: "Score trending upward",
  home_credit_down: "Score trending down",
  home_credit_flat: "Score holding steady",
  home_interest: "interest",
  home_up_to: "Up to",
  home_score_excellent: "Excellent",
  home_score_very_good: "Very Good",
  home_score_good: "Good",
  home_score_fair: "Fair",
  home_score_poor: "Poor",

  settings_title: "Settings",
  settings_general: "General Settings",
  settings_notifications: "Notifications",
  settings_personal_info: "Personal Information",
  settings_language: "Language",
  settings_security_privacy: "Security & Privacy",
  settings_security: "Security",
  settings_help_center: "Help Center",
  settings_submit_feedback: "Submit Feedback",
  settings_danger_zone: "Danger Zone",
  settings_close_account: "Close Account",
  settings_log_out: "Log Out",
  settings_sign_out: "Sign Out",
  settings_sign_out_confirm: "Are you sure you want to sign out?",
  settings_close_account_confirm: "This action is irreversible. All your data will be permanently deleted.",

  advisor_title: "AI Advisor",
  advisor_total: "Total",
  advisor_this_month: "This Month",
  advisor_recent: "Recent",
  advisor_newest: "Newest",
  advisor_oldest: "Oldest",
  advisor_most_messages: "Most Messages",
  advisor_sort_by: "Sort by",
  advisor_no_conversations: "No Conversations Yet",
  advisor_start_chatting: "Start chatting with your AI financial advisor",
  advisor_start_conversation: "Start a Conversation",
  advisor_messages: "Messages",

  chat_title: "Kakasa Advisor",
  chat_how_help: "How can I help you today?",
  chat_ask_about: "Ask me about loans, credit scores, budgeting, or financial planning.",
  chat_improve_credit: "Improve my credit score",
  chat_compare_providers: "Compare loan providers",
  chat_help_budget: "Help me budget",
  chat_check_eligibility: "Check loan eligibility",
  chat_type_placeholder: "Type to start chatting...",
  chat_translate: "Translate",
  chat_hide_translation: "Hide translation",
  chat_translating: "Translating...",
  chat_connection_error: "Connection Error",
  chat_trouble_connecting: "I'm having trouble connecting right now. Please try again in a moment.",
  chat_translation_failed: "Translation Failed",
  chat_translation_failed_msg: "Could not translate this message. Please try again.",
  chat_language_required: "Language Required",
  chat_select_language: "Select a language other than English in Settings > Language to use translation.",

  notifications_title: "Notifications",
  notifications_no_notifications: "No Notifications",
  notifications_caught_up: "You're all caught up! We'll notify you when something important happens.",
  notifications_today: "Today",
  notifications_yesterday: "Yesterday",
  notifications_this_week: "This Week",

  personal_info_title: "Personal Information",
  personal_info_full_name: "Full Name",
  personal_info_dob: "Date of Birth",
  personal_info_profile_picture: "Choose Your Profile Picture",
  personal_info_location: "Location",
  personal_info_gender: "Gender",
  personal_info_choose_one: "Choose only 1",
  personal_info_male: "Male",
  personal_info_female: "Female",
  personal_info_save: "Save Settings",
  personal_info_saved: "Your personal information has been updated.",
  personal_info_name_placeholder: "Enter your full name",
  personal_info_location_placeholder: "City, District",
  personal_info_not_set: "Not set",
  personal_info_phone: "Phone Number",
  personal_info_phone_placeholder: "07XXXXXXXX",

  language_title: "Language",
  language_save: "Save Language",
  language_updated: "Language Updated",
  language_updated_message: "Your preferred language has been updated.",
  language_translating: "Translating app...",

  notif_settings_title: "Notification Settings",
  notif_loan_alerts: "Loan Alerts",
  notif_push: "Push Notifications",
  notif_payment_reminders: "Payment Reminders",
  notif_credit_updates: "Credit Score Updates",
  notif_sound_vibration: "Sound & Vibration",
  notif_sound: "Sound",
  notif_sound_desc: "When Sound Notifications are on, your phone will always check for sounds.",
  notif_vibration: "Vibration",
  notif_vibration_desc: "When Vibration Notifications are on, your phone will vibrate.",
  notif_misc: "Misc",
  notif_special_offers: "Special Offers",
  notif_app_updates: "App Updates",
  notif_resources: "Resources",
  notif_resources_desc: "Browse our collection of loan resources to improve your financial health.",
  notif_push_denied: "Notifications Disabled",
  notif_push_denied_msg: "Push notifications are disabled. Enable them in your device settings to receive loan updates and reminders.",
  notif_open_settings: "Open Settings",
  notif_disable_push: "Disable Push Notifications",
  notif_disable_push_msg: "To disable push notifications, turn them off in your device settings.",

  help_title: "Help Center",
  help_faq: "FAQ",
  help_live_chat: "Live Chat",
  help_search_placeholder: "Where can I f...",
  help_chat_heading: "We are here to help you with your loan needs!",
  help_chat_sub: "We aim to reply within a few minutes!",
  help_faq_q1: "What is Kakasa?",
  help_faq_a1: "Kakasa is a smart loan management app that helps you find, compare, and apply for loans from trusted Ugandan providers. We use AI to give personalized recommendations.",
  help_faq_q2: "How do I apply for a loan?",
  help_faq_a2: "Simply browse available loan providers, select a loan product that suits your needs, and follow the step-by-step application process within the app.",
  help_faq_q3: "How is my credit score calculated?",
  help_faq_a3: "Your credit score is calculated based on your financial history, repayment behavior, and other relevant data points from trusted credit bureaus.",
  help_faq_q4: "What loan providers are available?",
  help_faq_a4: "Kakasa partners with multiple trusted Ugandan financial institutions and microfinance providers to offer you a wide range of loan options.",
  help_faq_q5: "Is Kakasa free to use?",
  help_faq_a5: "Yes, Kakasa is completely free to download and use. We do not charge any fees for browsing, comparing, or applying for loans through our platform.",
  help_faq_q6: "Is my data secure?",
  help_faq_a6: "Absolutely. We use bank-level encryption and strict data protection policies to ensure your personal and financial information remains safe and private.",

  feedback_title: "Send Feedback",
  feedback_heading: "Which area needs improvement?",
  feedback_submit: "Submit Feedback",
  feedback_performance: "PERFORMANCE",
  feedback_bug: "BUG",
  feedback_ux: "USER EXPERIENCE",
  feedback_crashes: "CRASHES",
  feedback_loading: "LOADING",
  feedback_support: "SUPPORT",
  feedback_navigation: "NAVIGATION",

  loans_title: "Loans",
  loans_total_outstanding: "Total Outstanding",
  loans_your_loans: "Your Loans",
  loans_view_all: "View all",
  loans_no_loans: "No loans yet.",
  loans_load_error: "Could not load your loans. Please try again.",
  loans_chart_error: "Could not load chart data.",

  loan_details: "Loan Details",
  loan_outstanding: "Outstanding",
  loan_repaid: "repaid",
  loan_principal: "Principal",
  loan_interest_rate: "Interest rate",
  loan_term: "Term",
  loan_months: "months",
  loan_total_repayable: "Total repayable",
  loan_amount_paid: "Amount paid",
  loan_disbursed: "Disbursed",
  loan_due: "Due",
  loan_status: "Status",
  loan_payment_history: "Payment History",
  loan_no_payments: "No payments yet.",
  loan_not_found: "Not found",
  loan_not_found_msg: "This loan could not be found.",

  auth_sign_in: "Sign In To Kakasa",
  auth_sign_up: "Sign Up For Free",
  auth_email: "Email Address",
  auth_password: "Password",
  auth_email_placeholder: "you@example.com",
  auth_password_placeholder: "Enter your password...",
  auth_email_placeholder_alt: "Enter your email...",
  auth_sign_in_btn: "Sign In",
  auth_sign_up_btn: "Sign Up",
  auth_no_account: "Don't have an account?",
  auth_sign_up_link: "Sign Up.",
  auth_has_account: "Already have an account?",
  auth_sign_in_link: "Sign In.",
  auth_forgot_password: "Forgot Password",
  auth_forgot_subtitle: "Enter the email address associated with your account and we'll send you a link to reset your password.",
  auth_send_reset: "Send Reset Link",
  auth_remember_password: "Remember your password?",
  auth_missing_fields: "Missing fields",
  auth_missing_fields_msg: "Please enter your email and password.",
  auth_missing_email: "Missing email",
  auth_missing_email_msg: "Please enter your email address.",
  auth_sign_in_failed: "Sign in failed",
  auth_sign_up_failed: "Sign up failed",
  auth_google_failed: "Google sign-in failed",
  auth_reset_failed: "Reset failed",
  auth_weak_password: "Weak password",
  auth_weak_password_msg: "Password must be at least 6 characters.",
  auth_terms_required: "Terms required",
  auth_terms_required_msg: "Please agree to the Terms & Conditions.",
  auth_check_email: "Check your email",
  auth_check_email_signup: "We sent you a confirmation link. Please verify your email to continue.",
  auth_check_email_reset: "We sent you a password reset link. Please check your inbox.",
  auth_agree_with: "I Agree with",
  auth_terms: "Terms & Conditions",
  auth_something_wrong: "Something went wrong.",

  onboarding_get_started: "Get Started",
  onboarding_continue: "Continue",
  onboarding_finish: "Finish",
  onboarding_of: "OF",
  onboarding_purpose_heading: "What do you need a loan for?",
  onboarding_purpose_sub: "Select the category that best describes your need.",
  onboarding_purpose_business: "Business",
  onboarding_purpose_education: "Education",
  onboarding_purpose_medical: "Medical",
  onboarding_purpose_personal: "Personal",
  onboarding_purpose_agriculture: "Agriculture",
  onboarding_purpose_housing: "Housing",
  onboarding_employment_heading: "What's your employment status?",
  onboarding_employment_sub: "This helps us find the right loan options for you.",
  onboarding_employment_employed: "Employed",
  onboarding_employment_self: "Self-Employed",
  onboarding_employment_owner: "Business Owner",
  onboarding_employment_other: "Student / Other",
  onboarding_income_heading: "What's your monthly income?",
  onboarding_income_sub: "In Ugandan Shillings (UGX). Select the closest range.",
  onboarding_income_under_500k: "Under 500K",
  onboarding_income_500k_1m: "500K – 1M",
  onboarding_income_1m_2m: "1M – 2M",
  onboarding_income_2m_5m: "2M – 5M",
  onboarding_income_over_5m: "Over 5M",
  onboarding_income_per_month: "UGX/month",
  onboarding_amount_heading: "How much would you like to borrow?",
  onboarding_amount_sub: "Select an approximate amount in UGX.",
  onboarding_amount_selected: "You selected approximately",
  onboarding_history_heading: "Have you taken a loan before?",
  onboarding_history_sub: "This helps us understand your borrowing experience.",
  onboarding_yes: "Yes",
  onboarding_no: "No",
  onboarding_repayment_heading: "Preferred repayment period?",
  onboarding_repayment_sub: "Select one option.",
  onboarding_period_1m: "1 Month",
  onboarding_period_3m: "3 Months",
  onboarding_period_6m: "6 Months",
  onboarding_period_12m: "12 Months",
  onboarding_period_24m: "24 Months",
  onboarding_goals_heading: "Tell us about your financial goals",
  onboarding_goals_sub: "Freely write down what you'd like to achieve. This helps us personalize your experience.",
  onboarding_goals_placeholder: "E.g. I want to expand my business, pay school fees, build a house...",
  onboarding_error: "Something went wrong",

  setup_profile: "Profile Setup",
  setup_otp: "OTP Setup",
  setup_biometric: "Biometric Setup",
  setup_notifications: "Notification Setup",
  setup_continue: "Continue",
  setup_send_otp: "Send OTP",
  setup_finish: "Finish",
  setup_avatar_heading: "Select your Avatar",
  setup_avatar_sub: "We have a set of customizable avatar. Or you can upload your own image from your local file.",
  setup_upload_profile: "Or upload your profile",
  setup_full_name: "Full Name",
  setup_email: "Email Address",
  setup_gender: "Gender",
  setup_location: "Location",
  setup_dob: "Date of Birth",
  setup_dob_placeholder: "YYYY-MM-DD",
  setup_nin: "National ID Number (NIN)",
  setup_nin_placeholder: "e.g. CM90012345PE1J",
  setup_nin_hint: "14 characters, exactly as shown on your national ID card",
  setup_name_placeholder: "Enter your full name",
  setup_gender_placeholder: "Select gender",
  setup_location_placeholder: "City, District",
  setup_select_gender: "Select Gender",
  setup_male: "Male",
  setup_female: "Female",
  setup_otp_heading: "OTP Verification",
  setup_otp_sub: "We will send a one time SMS message.\nCarrier rates may apply.",
  setup_phone_placeholder: "Phone number",
  setup_otp_enter: "Enter 6 digit OTP Code",
  setup_otp_sent: "We sent a verification code to your phone number.",
  setup_otp_invalid: "Invalid OTP. Try Again.",
  setup_phone_in_use: "This phone number is already registered to another account.",
  setup_otp_resend: "Didn't receive the OTP?",
  setup_otp_resend_link: "Re-send.",
  setup_face_id: "Face ID Setup",
  setup_fingerprint: "Fingerprint Setup",
  setup_face_id_desc: "Use Face ID to securely access your account and authorize transactions.",
  setup_fingerprint_desc: "Scan your fingerprint to make your account more secure.",
  setup_enable_face_id: "Enable Face ID",
  setup_enable_fingerprint: "Enable Fingerprint",
  setup_skip: "Skip for now",
  setup_verify_face: "Verify Face ID",
  setup_verify_fingerprint: "Scan your fingerprint",
  setup_use_passcode: "Use passcode",
  setup_auth_failed: "Authentication failed",
  setup_auth_failed_msg: "Please try again or skip for now.",
  setup_notif_heading: "Notification Setup",
  setup_notif_sub: "Choose which notifications you'd like to receive. You can change these later in settings.",
  setup_notif_loan_alerts: "Loan Alerts",
  setup_notif_payment: "Payment Reminders",
  setup_notif_promotions: "Promotions & Offers",
  setup_select_country: "Select country",
  setup_done: "Done",
  setup_search_countries: "Search countries",
  setup_error: "Something went wrong",

  period_day: "Day",
  period_week: "Week",
  period_month: "Month",
  period_year: "Year",

  status_active: "Active",
  status_paid: "Paid",
  status_overdue: "Overdue",
  status_pending: "Pending",

  chart_borrowed: "Borrowed",
  chart_repaid: "Repaid",

  notif_just_now: "Just now",
  notif_earlier_this_month: "Earlier This Month",

  common_save: "Save",
  common_cancel: "Cancel",
  common_ok: "OK",
  common_error: "Error",
  common_saved: "Saved",
  common_hi: "Hi",
  common_score: "Score",
  common_days: "days",
  common_today: "Today",
  common_yesterday: "Yesterday",

  apply_credit_check: "Credit Check",
  apply_checking_credit: "Checking your credit score...",
  apply_credit_passed: "Credit Check Passed",
  apply_credit_failed: "Credit Check Not Passed",
  apply_score_meets: "Your credit score meets the requirements for this provider.",
  apply_score_below: "Your credit score is below the minimum requirement for this provider.",
  apply_continue: "Continue Application",
  apply_your_score: "Your Score",
  apply_required_score: "Required Score",
  apply_risk_level: "Risk Level",
  apply_loan_amount: "Loan Amount",
  apply_not_eligible: "Not Eligible",
  apply_not_eligible_msg: "You do not meet the eligibility requirements for this provider.",

  consent_title: "Loan Application Consent",
  consent_heading: "Before we proceed",
  consent_subheading: "Please review and agree to the following terms to continue with your loan application.",
  consent_data_collection: "Data Collection & Processing",
  consent_data_collection_desc: "We will collect and process your personal data, including identity verification, financial information, and employment details.",
  consent_credit_inquiry: "Credit Inquiry",
  consent_credit_inquiry_desc: "We will perform a soft credit inquiry which will not affect your credit score.",
  consent_ai_interview: "AI-Powered Interview",
  consent_ai_interview_desc: "You will participate in a voice-based interview with our AI assistant. The conversation will be recorded and analyzed.",
  consent_data_sharing: "Data Sharing",
  consent_data_sharing_desc: "Your application data may be shared with the loan provider for final decision processing.",
  consent_document_upload: "Document Upload",
  consent_document_upload_desc: "You may be asked to upload supporting documents such as ID, payslips, or employment contracts during the interview.",
  consent_agree: "I agree to the terms above",
  consent_proceed: "Proceed to Interview",
  consent_decline: "Decline & Go Back",

  interview_title: "AI Interview",
  interview_choose_mode: "Choose Interview Mode",
  interview_choose_mode_desc: "How would you like to conduct your interview?",
  interview_mode_voice: "Voice",
  interview_mode_voice_desc: "Speak with the AI interviewer using your microphone",
  interview_mode_text: "Text",
  interview_mode_text_desc: "Type your responses in a chat conversation",
  interview_start: "Start Interview",
  interview_type_placeholder: "Type your response...",
  interview_send: "Send",
  interview_connecting: "Connecting to interviewer...",
  interview_listening: "Listening...",
  interview_thinking: "Processing...",
  interview_speaking: "AI is speaking...",
  interview_tap_to_speak: "Tap to speak",
  interview_release_to_send: "Release to send",
  interview_tap_to_send: "Tap to send",
  interview_recording: "Recording...",
  interview_upload_document: "Upload Document",
  interview_take_photo: "Take Photo",
  interview_choose_file: "Choose File",
  interview_cancel: "Cancel",
  interview_document_received: "Document received",
  interview_end_interview: "End Interview",
  interview_end_confirm: "Are you sure you want to end the interview? Your application will be submitted for review.",
  interview_end_yes: "End & Submit",
  interview_muted: "Muted",
  interview_unmuted: "Unmuted",
  interview_elapsed: "Elapsed",
  interview_transcript: "Transcript",
  interview_mic_permission: "Microphone Permission Required",
  interview_mic_permission_msg: "Please allow microphone access to participate in the voice interview.",
  interview_error: "Interview Error",
  interview_error_msg: "Something went wrong during the interview. Please try again.",
  interview_greeting: "Hello! I'm your loan interview assistant. I'll ask you a few questions about your application. Shall we begin?",

  decision_title: "Application Decision",
  decision_reviewing: "Reviewing your application...",
  decision_approved: "Application Approved!",
  decision_declined: "Application Not Approved",
  decision_in_review: "Under Review",
  decision_approved_msg: "Congratulations! Your loan has been approved and disbursed to your mobile money.",
  decision_declined_msg: "Unfortunately, your application was not approved at this time.",
  decision_review_msg: "Your application needs additional review. We'll notify you within 24 hours.",
  decision_score: "Interview Score",
  decision_factors: "Key Factors",
  decision_next_steps: "Next Steps",
  decision_disbursed_to: "Disbursed to",
  decision_amount_sent: "Amount Sent",
  decision_approved_next: "Your funds have been sent to your mobile money number. Check your phone for the transaction confirmation.",
  decision_declined_next: "You can improve your profile and try again later, or explore other providers.",
  decision_review_next: "Sit tight — we'll send you a notification once the review is complete.",
  decision_back_home: "Back to Home",
  decision_view_providers: "View Other Providers",
  decision_try_again: "Try Another Provider",

  pay_title: "Make Payment",
  pay_outstanding: "Outstanding Balance",
  pay_amount: "Payment Amount",
  pay_mobile_money: "Mobile Money",
  pay_visa_card: "Visa Card",
  pay_phone: "Phone Number",
  pay_card_number: "Card Number",
  pay_expiry: "Expiry",
  pay_cvv: "CVV",
  pay_button: "Pay",
  pay_success: "Payment Successful!",
  pay_success_msg: "Your payment has been processed successfully.",
  pay_receipt_number: "Receipt No.",
  pay_view_receipt: "View Receipt",
  pay_back_to_loan: "Back to Loan",
  pay_invalid_amount: "Invalid Amount",
  pay_invalid_amount_msg: "Please enter a valid payment amount.",
  pay_exceeds_balance: "Amount Exceeds Balance",
  pay_exceeds_balance_msg: "Payment amount cannot exceed the outstanding balance.",
  pay_phone_required: "Phone number is required for mobile money payments.",
  pay_card_required: "Card details are required for card payments.",
  pay_processing: "Processing payment...",
  pay_make_payment: "Make Payment",

  receipt_title: "Payment Receipt",
  receipt_number: "Receipt No.",
  receipt_date: "Date",
  receipt_transaction_ref: "Transaction Ref",
  receipt_amount_paid: "Amount Paid",
  receipt_payment_method: "Payment Method",
  receipt_phone: "Phone",
  receipt_card: "Card",
  receipt_provider: "Provider",
  receipt_loan_id: "Loan ID",
  receipt_previous_balance: "Previous Balance",
  receipt_remaining_balance: "Remaining Balance",
  receipt_thank_you: "Thank you for your payment",
  receipt_completed: "Completed",
  receipt_share: "Share Receipt",
  receipt_download: "Download Receipt",
  receipt_not_found: "Receipt not found",
  receipt_not_found_msg: "This payment receipt could not be found.",

  ussd_welcome: "Welcome to Kakasa USSD",
  ussd_register: "Register",
  ussd_repay: "Repay",
  ussd_credit_score: "Credit Score",
  ussd_lenders: "Eligible Lenders",
  ussd_help: "Help",
  ussd_language: "Language",
};
